@startuml
package user_package as "Микросервис управления пользователямми" {
    entity user {
        * id
        email
        password
        created_at
        updated_at
        status
    }
    
    entity house {
        * id
        user_id [FK to user.id]
        address
        created_at
        updated_at
        status

    }
    user --{ house

}

package device_package as "Микросервис управления устройствами" {
    entity device {
        * id
        user_id [FK to user.id]
        house_id [FK to house.id]
        status
        current_temperature
        brightness
        isOpen
        created_at
        updated_at
        device_type_code [FK to device_type.code]
        name
        serial_number
    }

    entity device_type {
        * id
        code 
        description
        status
    }

    device --* device_type
}

package telemetry as "Микросервис телеметрии" {
    entity telemetry_data {
        * id
        device_id
        house_id
        brightness
        current_temperature
        isOn
        video_data
    }
}

house -L-{ device
user -L-{ device

telemetry -R-{ device

@enduml
