@startuml
!include ./C4_Container.puml

Enterprise_Boundary(e1, "Система управления отоплением") {
    System_Boundary(s1, "Домен: Управление отоплением"){
        Container(backend, "Сабдомен: Система отопления", "java", "Позволяет пользователю управлять температурой и включать/выключать отопление")
        Container(backend_api, "Сабдомен: Система температурных датчиков", "java", "Позволяет синхронизировать данные между датчиками о температуре")
    }
}

@enduml